### ISSUE TITLE
Weather Underground

### ISSUE THREAD

**Issue by eboston** [Bodmer/esp8266-weather-station-color#1]
Now that weather underground has given the middle finger to the community that helped it became what it is, has there been any work with this to switch to a different provider?  I see that ThingPulse has converted over to Open Weather Map and I was thinking of trying to update this code to also use it, if it hasn't been done.

**Comment by MarcFinns** [comment]
i am also interested. I see that the original Squix weatherstation has moved to openweathermap but the code has dramatically changed. Specifically, they use their own graphic libs, a pity. 
It looks like a full rewrite rather than a simple port.
Has anyone started or even succeeded?

**Comment by Bodmer** [comment]
Hi, as it happens I have been looking at this recently. I am writing a weather data retrieval library that uses the [Dark Sky weather API](https://darksky.net/dev) that will be posted on Github soon. Dark Sky allow up to 1000 calls a day free, and no billing information needs to be provided for this. This provides global weather data but uses secure https, which is supported by the ESP8266 . I have a Beta version running with an example sketch that has serial text output only at the moment just to test the library.  I will try an post the beta version later today. The aim is then to port the weather station color sketch to use that library.

ThingPulse has a general purpose [weather data access library](https://github.com/ThingPulse/esp8266-weather-station/tree/master/examples) that could also be used, this supports the UK Met Office API (UK only weather) as well as OpenWeatherMap.  Some of the examples do not use a TFT and just show how to fetch the weather data, so this is worth a look.

**Comment by MarcFinns** [comment]
Hi Bodmer, I was also looking at these two options. Openweathermap seems to be less precise (at least in my area). The libs you mention require a lot of stitching as they significantly changed the approach. I was about to convince myself to do it but in fact darksky seems better. With esp 2.4.2 they integrated BearSSL and it works so much better than the previous library. I resumed some projects that would simply crash with out of memory. Let me know if you plan on doing it.

**Comment by Bodmer** [comment]
I've posted the [DarkSkyWeather library](https://github.com/Bodmer/DarkSkyWeather) "as is".

It is still in development but runs fine for me.

**Comment by MarcFinns** [comment]
Are you using BearSSL or axTLS?

**Comment by Bodmer** [comment]
Uses axTSL, BearSSL has not been tried but may be more stable when RAM is in short supply.  I have [added an alternative line](https://github.com/Bodmer/DarkSkyWeather/blob/master/DarkSkyWeather.cpp#L30) for the BearSSL namespace as a reminder to try it at some point.

**Comment by MarcFinns** [comment]
Traveling now but I will have a look, thanks. Indeed I confirm that there is a huge gap between the two. With bear you can also explicitly specify the size of tx/RX buffers. Let me know if you plan the stitching into the old weather station...

**Comment by Bodmer** [comment]
I will be doing a quick hack soon to use the library but in the longer term I want a more standardised data access API to the library so I can swap in other weather datapoint provider libraries more easily in case Dark Sky pull the plug on free access.

Longer term plan, given time, is to use the ESP32 with PSRAM.

**Comment by MarcFinns** [comment]
Indeed the ESP32-WROVER thing is a cool development in this space but not sure if strictly needed for this specific application!

**Comment by MarcFinns** [comment]
On a semi-related subject, I started from your version of the plane spotter and integrated it in a larger project of mine some time ago. It was working properly for a long time but I now see it is not anymore. I am wondering whether this is yet another api change. Have you noticed the same issues?

**Comment by MarcFinns** [comment]
Forgot: If you use BearSSL, you can solve the refresh of the SHA fingerprint using 
client.setInsecure();

**Comment by Bodmer** [comment]
The Dark Sky Weather library has been updated and includes the "final" version of the TFT example.

@MarcFinns I have not used Plane Spotter for some time so am unable to comment on that.  BearSSL and insecure client is the default in the Weather library, it seems to run fine for days.

**Comment by MarcFinns** [comment]
thanks

**Comment by MarcFinns** [comment]
Cool! i was probably the first one to give it a try...
Are the icons also available?

**Comment by Bodmer** [comment]
The icons are in the sketch data folder so must be uploaded to the ESP8266 SPIFFS using the IDE.
