### ISSUE TITLE
Clock with second digit

### ISSUE THREAD

**Issue by arindamc16** [Bodmer/esp8266-weather-station-color#3]
Thanks bodmer for creating such excellent project.
I want to know is it possible use SQUIX type clock with option for second digit display ? your clock only shows hour and minute but I need second also.

**Comment by Bodmer** [comment]
You can adapt the sketch. Maybe change[ these lines ](https://github.com/Bodmer/esp8266-weather-station-color/blob/master/esp8266-weather-station-color.ino#L313-L317)to:
```
  String timeNow = timeClient.getHours() + ":" + timeClient.getMinutes() + ":" + timeClient.getSeconds();

  tft.setTextDatum(BC_DATUM);
  tft.setTextColor(TFT_YELLOW, TFT_BLACK);
  tft.setTextPadding(tft.textWidth(" 44:44:44 "));  // String width + margin
```

will work, but this is untested. Be aware that the library is now deprecated so it will not be developed further.

**Comment by arindamc16** [comment]
Received following error


Arduino: 1.8.13 (Windows Store 1.8.42.0) (Windows 10), Board: "ESP32 Dev Module, Disabled, No OTA (2MB APP/2MB SPIFFS), 240MHz (WiFi/BT), QIO, 80MHz, 4MB (32Mb), 921600, None"



WARNING: library Timezone claims to run on avr architecture(s) and may be incompatible with your current board which runs on esp32 architecture(s).

C:\Users\LabPc\Desktop\Bodmer\OpenWeather-master\examples\TFT_eSPI_OpenWeather\TFT_eSPI_OpenWeather.ino: In function 'void drawTime()':

TFT_eSPI_OpenWeather:313:20: error: 'timeClient' was not declared in this scope

   String timeNow = timeClient.getFormattedTime();

                    ^

Multiple libraries were found for "SD.h"

 Used: C:\Users\LabPc\Documents\ArduinoData\packages\esp32\hardware\esp32\1.0.4\libraries\SD

 Not used: C:\Program Files\WindowsApps\ArduinoLLC.ArduinoIDE_1.8.42.0_x86__mdqgnx93n4wtt\libraries\SD

Multiple libraries were found for "WiFi.h"

 Used: C:\Users\LabPc\Documents\ArduinoData\packages\esp32\hardware\esp32\1.0.4\libraries\WiFi

 Not used: C:\Program Files\WindowsApps\ArduinoLLC.ArduinoIDE_1.8.42.0_x86__mdqgnx93n4wtt\libraries\WiFi

exit status 1

'timeClient' was not declared in this scope

**Comment by Bodmer** [comment]
This repository is an Arduino sketch for the ESP8266, the edits I suggested were for that sketch only.

**Comment by arindamc16** [comment]
I had successfully run the program on ESP32. Thanks.
![20210126_013522](https://user-images.githubusercontent.com/69916224/106037911-4b39be80-60fd-11eb-8e24-6e8e3743c6f7.jpg)
